### PR TITLE
t raFeature/issue 6 merging upstream rapidpro

### PR DESCRIPTION
**Pull request by bruskiza**
Updating the praekelt version to the latest rapidpro.

### CODE REVIEW

**Comment by bruskiza** [comment]
@smn @jerith here is the merge.
The main thing u need to look at is: https://github.com/praekelt/rapidpro/commit/fbbaf9bb93e413dec9e307f0da33c11189d24fbf

It's me resolving conflicts between our rapidpro and theirs.

**Comment by smn** [comment]
I'm a little uncomfortable going forward with this. Would it not be easier to re-clone and re-apply whatever changes we made rather than doing a merge? 

Sorry I know this is a bit of a hassle.

**Comment by bruskiza** [comment]
Will do... no problems.

**Comment by bruskiza** [comment]
Closing this... starting again.

**Pull request closed without merging**
